Replace deprecated 'Mojo::File::spew' with 'spurt'
This fixes issues like observed in
https://github.com/openSUSE/qem-dashboard/actions/runs/16056912984/job/45313482646?pr=2666#step:11:13

```
Error: Mojo::File::spurt is deprecated in favor of Mojo::File::spew at /opt/hostedtoolcache/perl/5.40.2/x64/lib/site_perl/5.40.2/Mojo/Alien/webpack.pm line 187.
```

same as local test errors using a current Mojolicious distribution like

```
t/plugin-built.t ............. Mojo::File::spurt is deprecated in favor of Mojo::File::spew at t/plugin-built.t line 24.
Mojo::File::spurt is deprecated in favor of Mojo::File::spew at t/plugin-built.t line 32.
```